[features]
seeds = false
skip-lint = false
[programs.devnet]
gifsonchain = "DcJUJ1FNVNHy9iihgDJ9f5B8C7KpvEh4cF8ZjwckfKYZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/danilkuznecov/.config/solana/id.json"

[scripts]
test = "node tests/gifsonchain.js"
